Anypoint Valomnia Connector Demo
==================================


INTRODUCTION
------------
   .

HOW TO RUN DEMO
---------------

### Prerequisites
In order to build and run this project, you'll need;

* Anypoint Studio with Mule ESB 3.8 Runtime.
* Anypoint Valomnia v1.0.0
* Access to Valomnia account

### Test the flows

With Anypoint Studio up and running, open the Import wizard from the File menu. A pop-up wizard will offer you the chance to pick Anypoint Studio Project from External Location. On the next wizard window point Project Root to the location of the demo project and select the Server Runtime as Mule Server 3.8.0 CE or EE. Once successfully imported the studio will automatically present the Anypoint Flows.

From the Package Explorer view, expand the demo project and open the mule-app.properties file. Fill in the credentials of Valomnia account. 

#### Valomnia-operations-demo :

* Run the demo project.
* In web browser visit http://localhost:8081/Valomnia to view the demo page. The page displays the Buttons to invoke the operation defined by the flows.

While the demo project is up and running you can also directly visit the below URL's to view the output of individual flows.

* Get Items : http://localhost:8081/Valomnia/FindItems
* Save Item : http://localhost:8081/Valomnia/SaveOrUpdateItem

SUMMARY
-------

Congratulations! The demo presents only a limited list of operations to play with, refer to the connector user manual for all the operations supported and further possibilities.